server:
  port: 8067
  servlet:
    context-path: /api
exchange-rate:
  api:
    url:  https://api.exchangerate-api.com/v4/latest/
    key: 69c4fef3de1c680f1356502a62149df4
  # Should be passed as environment variable
spring:
  security:
    user:
      name: user
      password: password
  application:
    name: rate-service

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
